
set(CPACK_PACKAGE_CONTACT "neshkeev@yandex.ru")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A Bash's pipe-like operator for C++")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
set(CPACK_PACKAGE_VERSION_MAJOR "${cppipe_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${cppipe_VERSION_MINOR}")

include(CPack)
